version: "3"
services:

    webserver:
        image: nginx:stable-perl
        restart: always
        container_name: nginx
        expose:
            - "80"
        ports:
            - 8080:80
        hostname: server
        volumes:
            - ./nginx:/usr/share/nginx/html:ro
        networks:
            - network

    rabbit_mq:
        image: rabbitmq:3.10.7-management
        container_name: rabbit_mq
        hostname: rabbitmq
        restart: always
        volumes:
            - rabbit_mqdata:/usr/share/rabbitmq/data
        ports:
            - 15672:15672
            
    producer:
        build: producer
        depends_on:
            - rabbit_mq
        volumes:
            - ./producer:/usr/src/app/producer
            
    consumer:
        build: consumer
        depends_on:
            - rabbit_mq
        volumes:
            - ./consumer:/usr/src/app/consumer
            
volumes:
    rabbit_mqdata:
        driver: local

networks:
    network:
        driver: bridge